server:
  port: 8088

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: LoTs
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
        format_sql: true
        use_sql_comments: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    
  security:
    user:
      # name: ${SPRING_SECURITY_USER_NAME}
      # password: ${SPRING_SECURITY_USER_PASSWORD}
      name: gani
      password: gksrkdms

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30 minutes